
version: 2

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: docs/

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
