name: Run tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .[test,dev]

    - name: Run pre-commit
      run: |
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    - name: Check for syntax errors and lint with flake8
      run: |
        # check for important errors:
        # - syntax errors (E9),
        # - confusion between assignment and equality errors (F63),
        # - logic errors and syntax errors in type hints (F7)
        # - undefined name errors (F82)
        flake8 . \
            --count --select=E9,F63,F7,F82 --show-source --statistics
        # display all other linting errors, but never return an error code
        flake8 . \
            --count \
            --statistics

    - name: Run tests with pytest
      run: |
        # run tests with pytest, reporting coverage and timings
        pytest -m "not slow" -rs -vvv  --durations=0 --cov=./modnet/
